namespace KuGou.Lite;

public sealed class KugouAiRecommendResponseDto : KugouRouteResponseDto { }
public sealed class KugouAlbumResponseDto : KugouRouteResponseDto { }
public sealed class KugouAlbumDetailResponseDto : KugouRouteResponseDto { }
public sealed class KugouAlbumShopResponseDto : KugouRouteResponseDto { }
public sealed class KugouAlbumSongsResponseDto : KugouRouteResponseDto { }
public sealed class KugouArtistAlbumsResponseDto : KugouRouteResponseDto { }
public sealed class KugouArtistAudiosResponseDto : KugouRouteResponseDto { }
public sealed class KugouArtistDetailResponseDto : KugouRouteResponseDto { }
public sealed class KugouArtistFollowResponseDto : KugouRouteResponseDto { }
public sealed class KugouArtistFollowNewsongsResponseDto : KugouRouteResponseDto { }
public sealed class KugouArtistHonourResponseDto : KugouRouteResponseDto { }
public sealed class KugouArtistListsResponseDto : KugouRouteResponseDto { }
public sealed class KugouArtistUnfollowResponseDto : KugouRouteResponseDto { }
public sealed class KugouArtistVideosResponseDto : KugouRouteResponseDto { }
public sealed class KugouAudioResponseDto : KugouRouteResponseDto { }
public sealed class KugouAudioAccompanyMatchingResponseDto : KugouRouteResponseDto { }
public sealed class KugouAudioKtvTotalResponseDto : KugouRouteResponseDto { }
public sealed class KugouAudioRelatedResponseDto : KugouRouteResponseDto { }
public sealed class KugouBrushResponseDto : KugouRouteResponseDto { }
public sealed class KugouCaptchaSentResponseDto : KugouRouteResponseDto { }
public sealed class KugouCommentAlbumResponseDto : KugouRouteResponseDto { }
public sealed class KugouCommentCountResponseDto : KugouRouteResponseDto { }
public sealed class KugouCommentFloorResponseDto : KugouRouteResponseDto { }
public sealed class KugouCommentMusicResponseDto : KugouRouteResponseDto { }
public sealed class KugouCommentMusicClassifyResponseDto : KugouRouteResponseDto { }
public sealed class KugouCommentMusicHotwordResponseDto : KugouRouteResponseDto { }
public sealed class KugouCommentPlaylistResponseDto : KugouRouteResponseDto { }
public sealed class KugouEverydayFriendResponseDto : KugouRouteResponseDto { }
public sealed class KugouEverydayHistoryResponseDto : KugouRouteResponseDto { }
public sealed class KugouEverydayRecommendResponseDto : KugouRouteResponseDto { }
public sealed class KugouEverydayStyleRecommendResponseDto : KugouRouteResponseDto { }
public sealed class KugouFavoriteCountResponseDto : KugouRouteResponseDto { }
public sealed class KugouFmClassResponseDto : KugouRouteResponseDto { }
public sealed class KugouFmImageResponseDto : KugouRouteResponseDto { }
public sealed class KugouFmRecommendResponseDto : KugouRouteResponseDto { }
public sealed class KugouFmSongsResponseDto : KugouRouteResponseDto { }
public sealed class KugouImagesResponseDto : KugouRouteResponseDto { }
public sealed class KugouImagesAudioResponseDto : KugouRouteResponseDto { }
public sealed class KugouIpResponseDto : KugouRouteResponseDto { }
public sealed class KugouIpDateilResponseDto : KugouRouteResponseDto { }
public sealed class KugouIpPlaylistResponseDto : KugouRouteResponseDto { }
public sealed class KugouIpZoneResponseDto : KugouRouteResponseDto { }
public sealed class KugouIpZoneHomeResponseDto : KugouRouteResponseDto { }
public sealed class KugouKmrAudioMvResponseDto : KugouRouteResponseDto { }
public sealed class KugouKrmAudioResponseDto : KugouRouteResponseDto { }
public sealed class KugouLastestSongsListenResponseDto : KugouRouteResponseDto { }
public sealed class KugouLoginResponseDto : KugouRouteResponseDto { }
public sealed class KugouLoginCellphoneResponseDto : KugouRouteResponseDto { }
public sealed class KugouLoginDeviceResponseDto : KugouRouteResponseDto { }
public sealed class KugouLoginDeviceKickResponseDto : KugouRouteResponseDto { }
public sealed class KugouLoginOpenplatResponseDto : KugouRouteResponseDto { }
public sealed class KugouLoginQrCheckResponseDto : KugouRouteResponseDto { }
public sealed class KugouLoginQrCreateResponseDto : KugouRouteResponseDto { }
public sealed class KugouLoginQrKeyResponseDto : KugouRouteResponseDto { }
public sealed class KugouLoginTokenResponseDto : KugouRouteResponseDto { }
public sealed class KugouLoginWxCheckResponseDto : KugouRouteResponseDto { }
public sealed class KugouLoginWxCreateResponseDto : KugouRouteResponseDto { }
public sealed class KugouLongaudioAlbumAudiosResponseDto : KugouRouteResponseDto { }
public sealed class KugouLongaudioAlbumDetailResponseDto : KugouRouteResponseDto { }
public sealed class KugouLongaudioDailyRecommendResponseDto : KugouRouteResponseDto { }
public sealed class KugouLongaudioRankRecommendResponseDto : KugouRouteResponseDto { }
public sealed class KugouLongaudioVipRecommendResponseDto : KugouRouteResponseDto { }
public sealed class KugouLongaudioWeekRecommendResponseDto : KugouRouteResponseDto { }
public sealed class KugouLyricResponseDto : KugouRouteResponseDto { }
public sealed class KugouPcDiantaiResponseDto : KugouRouteResponseDto { }
public sealed class KugouPersonalFmResponseDto : KugouRouteResponseDto { }
public sealed class KugouPlayhistoryUploadResponseDto : KugouRouteResponseDto { }
public sealed class KugouPlaylistAddResponseDto : KugouRouteResponseDto { }
public sealed class KugouPlaylistDelResponseDto : KugouRouteResponseDto { }
public sealed class KugouPlaylistDetailResponseDto : KugouRouteResponseDto { }
public sealed class KugouPlaylistEffectResponseDto : KugouRouteResponseDto { }
public sealed class KugouPlaylistSimilarResponseDto : KugouRouteResponseDto { }
public sealed class KugouPlaylistTagsResponseDto : KugouRouteResponseDto { }
public sealed class KugouPlaylistTrackAllResponseDto : KugouRouteResponseDto { }
public sealed class KugouPlaylistTrackAllNewResponseDto : KugouRouteResponseDto { }
public sealed class KugouPlaylistTracksAddResponseDto : KugouRouteResponseDto { }
public sealed class KugouPlaylistTracksDelResponseDto : KugouRouteResponseDto { }
public sealed class KugouPrivilegeLiteResponseDto : KugouRouteResponseDto { }
public sealed class KugouRankAudioResponseDto : KugouRouteResponseDto { }
public sealed class KugouRankInfoResponseDto : KugouRouteResponseDto { }
public sealed class KugouRankListResponseDto : KugouRouteResponseDto { }
public sealed class KugouRankTopResponseDto : KugouRouteResponseDto { }
public sealed class KugouRankVolResponseDto : KugouRouteResponseDto { }
public sealed class KugouRecommendSongsResponseDto : KugouRouteResponseDto { }
public sealed class KugouRegisterDevResponseDto : KugouRouteResponseDto { }
public sealed class KugouSceneAudioListResponseDto : KugouRouteResponseDto { }
public sealed class KugouSceneCollectionListResponseDto : KugouRouteResponseDto { }
public sealed class KugouSceneListsResponseDto : KugouRouteResponseDto { }
public sealed class KugouSceneListsV2ResponseDto : KugouRouteResponseDto { }
public sealed class KugouSceneModuleResponseDto : KugouRouteResponseDto { }
public sealed class KugouSceneModuleInfoResponseDto : KugouRouteResponseDto { }
public sealed class KugouSceneMusicResponseDto : KugouRouteResponseDto { }
public sealed class KugouSceneVideoListResponseDto : KugouRouteResponseDto { }
public sealed class KugouSearchResponseDto : KugouRouteResponseDto { }
public sealed class KugouSearchComplexResponseDto : KugouRouteResponseDto { }
public sealed class KugouSearchDefaultResponseDto : KugouRouteResponseDto { }
public sealed class KugouSearchHotResponseDto : KugouRouteResponseDto { }
public sealed class KugouSearchLyricResponseDto : KugouRouteResponseDto { }
public sealed class KugouSearchMixedResponseDto : KugouRouteResponseDto { }
public sealed class KugouSearchSuggestResponseDto : KugouRouteResponseDto { }
public sealed class KugouServerNowResponseDto : KugouRouteResponseDto { }
public sealed class KugouSheetCollectionResponseDto : KugouRouteResponseDto { }
public sealed class KugouSheetCollectionDetailResponseDto : KugouRouteResponseDto { }
public sealed class KugouSheetDetailResponseDto : KugouRouteResponseDto { }
public sealed class KugouSheetHotResponseDto : KugouRouteResponseDto { }
public sealed class KugouSheetListResponseDto : KugouRouteResponseDto { }
public sealed class KugouSingerListResponseDto : KugouRouteResponseDto { }
public sealed class KugouSongClimaxResponseDto : KugouRouteResponseDto { }
public sealed class KugouSongRankingResponseDto : KugouRouteResponseDto { }
public sealed class KugouSongRankingFilterResponseDto : KugouRouteResponseDto { }
public sealed class KugouSongUrlResponseDto : KugouRouteResponseDto { }
public sealed class KugouSongUrlNewResponseDto : KugouRouteResponseDto { }
public sealed class KugouThemeMusicResponseDto : KugouRouteResponseDto { }
public sealed class KugouThemeMusicDetailResponseDto : KugouRouteResponseDto { }
public sealed class KugouThemePlaylistResponseDto : KugouRouteResponseDto { }
public sealed class KugouThemePlaylistTrackResponseDto : KugouRouteResponseDto { }
public sealed class KugouTopAlbumResponseDto : KugouRouteResponseDto { }
public sealed class KugouTopCardResponseDto : KugouRouteResponseDto { }
public sealed class KugouTopCardYouthResponseDto : KugouRouteResponseDto { }
public sealed class KugouTopIpResponseDto : KugouRouteResponseDto { }
public sealed class KugouTopPlaylistResponseDto : KugouRouteResponseDto { }
public sealed class KugouTopSongResponseDto : KugouRouteResponseDto { }
public sealed class KugouUserCloudResponseDto : KugouRouteResponseDto { }
public sealed class KugouUserCloudUrlResponseDto : KugouRouteResponseDto { }
public sealed class KugouUserDetailResponseDto : KugouRouteResponseDto { }
public sealed class KugouUserFollowResponseDto : KugouRouteResponseDto { }
public sealed class KugouUserFollowMessageResponseDto : KugouRouteResponseDto { }
public sealed class KugouUserHistoryResponseDto : KugouRouteResponseDto { }
public sealed class KugouUserListenResponseDto : KugouRouteResponseDto { }
public sealed class KugouUserPlaylistResponseDto : KugouRouteResponseDto { }
public sealed class KugouUserVideoCollectResponseDto : KugouRouteResponseDto { }
public sealed class KugouUserVideoLoveResponseDto : KugouRouteResponseDto { }
public sealed class KugouUserVipDetailResponseDto : KugouRouteResponseDto { }
public sealed class KugouVideoDetailResponseDto : KugouRouteResponseDto { }
public sealed class KugouVideoPrivilegeResponseDto : KugouRouteResponseDto { }
public sealed class KugouVideoUrlResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthChannelAllResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthChannelAmwayResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthChannelDetailResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthChannelSimilarResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthChannelSongResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthChannelSongDetailResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthChannelSubResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthDayVipResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthDayVipUpgradeResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthDynamicResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthDynamicRecentResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthListenSongResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthMonthVipRecordResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthUnionVipResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthUserSongResponseDto : KugouRouteResponseDto { }
public sealed class KugouYouthVipResponseDto : KugouRouteResponseDto { }
public sealed class KugouYuekuResponseDto : KugouRouteResponseDto { }
public sealed class KugouYuekuBannerResponseDto : KugouRouteResponseDto { }
public sealed class KugouYuekuFmResponseDto : KugouRouteResponseDto { }
