<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <AssemblyName>KuGouLiteSdk</AssemblyName>
    <RootNamespace>KuGou.Lite</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

</Project>
