<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-ios</TargetFramework>
    <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.iOS" />
  </ItemGroup>

  <ItemGroup>
    <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Contents.json" />
    <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\*.png" />
    <ImageAsset Include="Assets.xcassets\LaunchLogo.imageset\Contents.json" />
    <ImageAsset Include="Assets.xcassets\LaunchLogo.imageset\*.png" />
    <InterfaceDefinition Include="Resources\LaunchScreen.xib" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KuGouMusicAvalonia\KuGouMusicAvalonia.csproj" />
  </ItemGroup>
</Project>
