<Project>
  <PropertyGroup>
    <!-- Manually maintain unified app version here for all platforms. -->
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <InformationalVersion>1.0.1</InformationalVersion>

    <!-- Android version code must be an integer and should increase monotonically. -->
    <AppVersionCode>2</AppVersionCode>
  </PropertyGroup>
</Project>
